version: "3.9"
services:
  django-server:
    build:
      context: ..
      dockerfile: ./LibraryMetricScripts/docker/Dockerfile
    container_name: "librarycomparison"
    volumes:
      - "./LibraryMetricScripts/librarycomparison:/app"
    ports:
      - "8000:8000"
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
       MYSQL_DATABASE: "libcomp"
       MYSQL_USER: "root"
       MYSQL_PASSWORD: "password"
       MYSQL_ROOT_PASSWORD: "password"
